### ISSUE TITLE
Quotation marks aren't "TeX-style"

### ISSUE THREAD

**Issue by robpieke** [AcademySoftwareFoundation/OpenShadingLanguage#1014]
Yes, I'm *that* bored :)

Some of the quoted text in the TeX documentation uses "" rather than ``''. I've done a pass at changing this and will submit a PR.

**Comment by lgritz** [comment]
Cool, thanks!

BTW, there's no need to submit an "issue" and then immediately a PR. Just the PR can serve both purposes. Mainly the "issue" is for when you have identified a problem but you don't have a solution for it. (Or, I guess, if you are working on a solution but it won't be complete for some time, so you want people to know you're already working on it so that nobody else does the same thing redundantly.)

**Comment by robpieke** [comment]
Gotcha!

**Comment by lgritz** [comment]
I'm going to close this old issue because we've switched the main docs from LaTeX to markdown/RTD anyway.
