### ISSUE TITLE
New optix7 device strings

### ISSUE THREAD

**Issue by pellerington** [AcademySoftwareFoundation/OpenShadingLanguage#1350]
Hey I'm just trying out the latest changes to strings for optix 7 and I wanted to know the intended functionality. As I understand it, no strings are being stored on the GPU anymore, and you will instead be passed a hash of the strings location.

In the example raytracer you use this in the osl_printf function by writing the hash to a buffer which the CPU will read and then display.

What is the intented functionality for the other functions which require strings, for example osl_get_attribute or setting a microfacet distribution.

Is it still up to the user to allocate that memory on the GPU themselves and map that to the hash? Or is the intention that the user work with the hashes instead of strings. (Eg. if I see x hash I need to know that's the ggx distribution).

Thanks

**Comment by cmstein** [comment]
Your understanding is correct -- in OptiX 7+ on the GPU we have switched
from using strings to using their equivalent ustring hash.   You're not
passed a hash of the string's location -- it's the hash of the string
itself.  And these hashes are computed at shader compile time by OSL and
are inlined in the PTX code, so there's no need to store them on the GPU.

This was done to help ameliorate some of the long compilation times when
loading device code.  Because the string hashes are always the same it
means that we can take advantage of the driver's compilation cache
(otherwise the driver would be re-compiling PTX code each render because
string addresses could've changed).

From the renderer implementation side (like rend_lib.cu), wherever you'd
expect to get a string, you'd get a hash.

For printing from shaders, does necessitate that the GPU and the CPU must
be in sync w.r.t. string<->hash mappings so that messages can be printed
correctly (thus the CPU needs to be aware of the compile-time strings which
it gets through the render services).

Once I get around to integrating these latest changes into our renderer, I
do intend to write up an implementation guide for inclusion in the OSL docs.

--cliff

**Comment by lgritz** [comment]
On the OptiX side, the "strings" *are* the hashes. So you can just compare them (if you use a recent OIIO build, we guarantee the hashes are unique). 

Things like concat and strlen ought to be resolved at the time that we JIT the shader, and turned into constants as far as the OptiX side is concerned. That does mean that when targeting the GPU, some things you used to be able to do in shaders (truly make unique strings in the middle of a shader that can't be figured out at JIT time) are not allowed. You ought to (eventually, if not now) get a clear warning about that so you know which operations in your shader can't be figured out.

There are so many missing pieces to the GPU implementation at the moment, we are just trying to prioritize. We wanted to get most of the basic string use in there with as little complication as possible, and then see, realistically, which remaining parts do people really need. So this isn't the final word on strings. We may switch implementations again later in ways that allow access to the characters, and maybe even let you create strings if that's truly important. But let's see how far we get with this approximation so we know where to put additional resources.

**Comment by pellerington** [comment]
Fantastic, thanks for explaining.

I was refering to comparing an OSL hash and a string I might have in my renderer.

For example if I want to access an attribute on my mesh (using osl_get_attribute), I need compare the hash with each of the attribute names on the mesh (stored as a string) to find it. 

I can either also store the hash of each of my (non-OSL) strings or use the inlined hash function on my string at runtime, correct?

Using the latter might be quite expensive if I also have to search for the object name as well. Maybe being able to register a pointer to the object at compile time (similar to register_string) would speedup as I wouldn't need to search through the objects.

Thanks for the help, knowing that concat/strlen are handled at JIT makes things much clearer.
